### PR TITLE
Update + Pin the version of sciencebeam to 0.0.1

### PR DESCRIPTION
**Pull request by diversemix**
Closes https://github.com/elifesciences/elife-xpub/issues/1190

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Note, this seems a much more recent version:
```
$ docker inspect elifesciences/sciencebeam:f05c51adbc49b47a65df1c3b7f69d25e401f5560 | jq .[].Created
"2018-08-24T18:30:22.270176619Z"
$ docker inspect elifesciences/sciencebeam:0.0.1 | jq .[].Created
"2018-12-17T02:09:44.200869961Z"
```

**Review by giorgiosironi — APPROVED** [review]

**Comment by diversemix** [comment]
:thinking: ... I looked here: https://hub.docker.com/r/elifesciences/sciencebeam/tags and assumed it would display the most recent first :doh:

**Comment by giorgiosironi** [comment]
There's no other deployment code where sciencebeam is used at the moment.

**Comment by giorgiosironi** [comment]
I'm all for upgrading now rather than once it is in use, but it may affect the metrics about the percentage of extracted titles and such.

**Comment by giorgiosironi** [comment]
`0.0.1` is probably the only versioned tag, and it's more recent than all other versions.

**Comment by diversemix** [comment]
Yes... I just had a chat with Daniel and he said to use the most recent one too ... so let me change the tag again. I think the ticket said `0.0.1` because that was the most recent at that time.

**Comment by de-code** [comment]
Apologies for the confusion. `0.0.1` seems to be indeed the last release version (@diversemix I thought yesterday you may have meant that there was a `0.0.2`). Commit tags should not be used anymore. Commit tags will now be added to [_unstable](https://hub.docker.com/r/elifesciences/sciencebeam_unstable/tags).
I also noticed an [issue with the release process](https://github.com/elifesciences/sciencebeam/issues/88).

**Pull request merged**
